# Generated by Django 4.1.1 on 2022-09-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_remove_usuario_edad_alter_usuario_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('genero', models.CharField(max_length=60)),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
