# Generated by Django 4.1.1 on 2022-10-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('genero', models.CharField(max_length=60)),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
