# Generated by Django 4.1.1 on 2022-10-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_delete_serie_delete_usuario_publi_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publi',
            name='imagen',
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
