# Generated by Django 4.1.1 on 2022-10-19 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0013_post_anio_post_genero_post_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='pp.png', null=True, upload_to='')),
                ('timecoment', models.DateTimeField(default=django.utils.timezone.now)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-timecoment'],
            },
        ),
        migrations.DeleteModel(
            name='Peli',
        ),
        migrations.DeleteModel(
            name='Publi',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='pp.png', null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='image',
            field=models.ImageField(default='pp.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
