# Generated by Django 4.1.1 on 2022-10-21 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0014_comentar_delete_peli_delete_publi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentar',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='AppCoder.post'),
        ),
    ]
