# Generated by Django 4.1.1 on 2022-10-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0015_alter_comentar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentar',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
