# Generated by Django 4.1.1 on 2022-10-21 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0016_alter_comentar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentar',
            name='image',
            field=models.ImageField(blank=True, default='pp.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comentar',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
