# Generated by Django 4.1.1 on 2022-10-22 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0017_alter_comentar_image_alter_comentar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentar',
            name='user',
        ),
        migrations.AddField(
            model_name='comentar',
            name='comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='AppCoder.post'),
        ),
    ]
