# Generated by Django 4.1.1 on 2022-10-22 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0018_remove_comentar_user_comentar_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentar',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='', null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='comentar',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
