# Generated by Django 4.1.1 on 2022-10-22 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0019_comentar_user_alter_avatar_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentar',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='image',
        ),
        migrations.AddField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comentar',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
